spring:
  application:
    name: movierecommendationsystem-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/movierecommendation
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties: 
      hibernate:          
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1039394498768-pa8127ndhi46mnu7f724vq5j9ffserlm.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8082/login/oauth2/code/google"
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo 

server:
  port: 8082
  error:
    include-message: always

tmdb:
  api.key: 1990523cf32528efb6e21f892955ba94
jwt:
  secret: 2+LaR6mKTpaFTMK4NKlHUQ5JgMtQFK0zGGSE/OUgJR8oU7Vhihb0gA8RofYlZZ/30kN+My5iIvuvYPDDMld5hg==
  expiration: 36000
